.TH "abstractmediainfo.h" 3 "Sat May 16 2015" "Blokbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
abstractmediainfo.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br
\fC#include <QString>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAbstractMediaInfo\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Blokbox from the source code\&.
