.TH "abstractspectrograph.h" 3 "Sat May 16 2015" "Blokbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
abstractspectrograph.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br
\fC#include <QVector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAbstractSpectrograph\fP"
.br
.RI "\fIThe \fBAbstractSpectrograph\fP class provides a generic interface for a spectrograph drawing widget\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Blokbox from the source code\&.
