.TH "html/search/all_6.js" 3 "Sat May 16 2015" "Blokbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
html/search/all_6.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['gotoitem',['goToItem',['\&.\&./class_main_window\&.html#a32e621ebdb3ef2d76bd607af16e8d0d0',1,'MainWindow']]],
  ['gradient',['gradient',['\&.\&./class_spectrograph\&.html#af1f07ee5e8b940b67d0d38c7b47d400e',1,'Spectrograph']]],
  ['gradientbrush',['gradientBrush',['\&.\&./class_spectrograph\&.html#ab244e2e23356d9dfe91acb9cc941f8e4',1,'Spectrograph']]],
  ['gravity',['gravity',['\&.\&./class_spectrograph\&.html#abababf3964842f53cfcbdcf6d80da8d8',1,'Spectrograph']]]
]
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Blokbox from the source code\&.
