.TH "html/search/all_12.js" 3 "Sat May 16 2015" "Blokbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
html/search/all_12.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['widgetheight',['widgetHeight',['\&.\&./class_spectrograph\&.html#a04c45c9c2515a0fefa8bd8b4cf1e9886',1,'Spectrograph']]],
  ['window',['window',['\&.\&./class_buffer_processor\&.html#ab0f8c0124e2b7d662ebb7f616d46b96f',1,'BufferProcessor']]]
]
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Blokbox from the source code\&.
