.TH "html/search/classes_0.js" 3 "Sat May 16 2015" "Blokbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
html/search/classes_0.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['abstractcontrol',['AbstractControl',['\&.\&./class_abstract_control\&.html',1,'']]],
  ['abstractmediainfo',['AbstractMediaInfo',['\&.\&./class_abstract_media_info\&.html',1,'']]],
  ['abstractspectrograph',['AbstractSpectrograph',['\&.\&./class_abstract_spectrograph\&.html',1,'']]]
]
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Blokbox from the source code\&.
