.TH "controls.h" 3 "Sat May 16 2015" "Blokbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
controls.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'abstractcontrol\&.h'\fP
.br
\fC#include <QTime>\fP
.br
\fC#include <QIcon>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBControls\fP"
.br
.RI "\fIThe \fBControls\fP class provides support to user control\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.RI "\fIThis is the namespace that defines the MainWindow1 ui widget\&. This is not the \fBMainWindow\fP class that is defined in this file\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Blokbox from the source code\&.
