.TH "html/search/defines_1.js" 3 "Sat May 16 2015" "Blokbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
html/search/defines_1.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['segment_5fheight',['SEGMENT_HEIGHT',['\&.\&./lightcycle_8h\&.html#a7fc7b75ac6c5689471af28b14cee9320',1,'lightcycle\&.h']]],
  ['specsize',['SPECSIZE',['\&.\&./fftcalc_8h\&.html#a999629c772b4e0df1e19b3481487a867',1,'fftcalc\&.h']]]
]
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Blokbox from the source code\&.
