.TH "html/dynsections.js" 3 "Sat May 16 2015" "Blokbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
html/dynsections.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "function \fBtoggleVisibility\fP (linkObj)"
.br
.ti -1c
.RI "function \fBupdateStripes\fP ()"
.br
.ti -1c
.RI "function \fBtoggleLevel\fP (level)"
.br
.ti -1c
.RI "function \fBtoggleFolder\fP (id)"
.br
.ti -1c
.RI "function \fBtoggleInherit\fP (id)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "function toggleFolder ( id)"

.SS "function toggleInherit ( id)"

.SS "function toggleLevel ( level)"

.SS "function toggleVisibility ( linkObj)"

.SS "function updateStripes ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Blokbox from the source code\&.
