.TH "html/search/enumvalues_1.js" 3 "Sat May 16 2015" "Blokbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
html/search/enumvalues_1.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['title',['Title',['\&.\&./class_playlist_model\&.html#a85df23455e37bba0806ef488fb96f435ad177ef9079b494b37664af91083db9f2',1,'PlaylistModel']]]
]
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Blokbox from the source code\&.
