.TH "fft.cpp" 3 "Sat May 16 2015" "Blokbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fft.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'fft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBfft\fP (\fBCArray\fP &\fBx\fP)"
.br
.RI "\fIfft calcs forward FFT transform \fP"
.ti -1c
.RI "void \fBifft\fP (\fBCArray\fP &\fBx\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void fft (\fBCArray\fP & x)"

.PP
fft calcs forward FFT transform 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP is the array to be transformed\&. The result is thrown directly onto it 
.RE
.PP

.SS "void ifft (\fBCArray\fP & x)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Blokbox from the source code\&.
