.TH "fftcalc.h" 3 "Sat May 16 2015" "Blokbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fftcalc.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QThread>\fP
.br
\fC#include <QWaitCondition>\fP
.br
\fC#include <QMutex>\fP
.br
\fC#include <QVector>\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include <QTimer>\fP
.br
\fC#include <QObject>\fP
.br
\fC#include 'fft\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBufferProcessor\fP"
.br
.RI "\fIThe \fBBufferProcessor\fP class is designed to process audio buffers sent by mainwindow\&. \fP"
.ti -1c
.RI "class \fBFFTCalc\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSPECSIZE\fP   512"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SPECSIZE   512"

.SH "Author"
.PP 
Generated automatically by Doxygen for Blokbox from the source code\&.
