.TH "fftcalc.cpp" 3 "Sat May 16 2015" "Blokbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fftcalc.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'fftcalc\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCLAMP\fP(a,  min,  max)   ((a) < (min) ? (min) : (a) > (max) ? (max) : (a))"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CLAMP(a, min, max)   ((a) < (min) ? (min) : (a) > (max) ? (max) : (a))"

.SH "Author"
.PP 
Generated automatically by Doxygen for Blokbox from the source code\&.
