.TH "html/search/files_5.js" 3 "Sat May 16 2015" "Blokbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
html/search/files_5.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['playlist_2eh',['playlist\&.h',['\&.\&./playlist_8h\&.html',1,'']]],
  ['playlistmodel_2ecpp',['playlistmodel\&.cpp',['\&.\&./playlistmodel_8cpp\&.html',1,'']]],
  ['playlistmodel_2eh',['playlistmodel\&.h',['\&.\&./playlistmodel_8h\&.html',1,'']]]
]
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Blokbox from the source code\&.
