.TH "html/search/functions_f.js" 3 "Sat May 16 2015" "Blokbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
html/search/functions_f.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['timerevent',['timerEvent',['\&.\&./class_light_cycle\&.html#a060f2eccc112b56017ca547861a64353',1,'LightCycle::timerEvent()'],['\&.\&./class_spectrograph\&.html#af690851ad862181732979bdfa88b2dbe',1,'Spectrograph::timerEvent()']]]
]
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Blokbox from the source code\&.
