.TH "html/search/functions_1.js" 3 "Sat May 16 2015" "Blokbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
html/search/functions_1.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['begininsertitems',['beginInsertItems',['\&.\&./class_playlist_model\&.html#a68bc9bedd81f59d1bf63b316b83063bc',1,'PlaylistModel']]],
  ['beginremoveitems',['beginRemoveItems',['\&.\&./class_playlist_model\&.html#a2b6c5632814de1d5fa705fb165f3633d',1,'PlaylistModel']]],
  ['bufferprocessor',['BufferProcessor',['\&.\&./class_buffer_processor\&.html#a910d84b159f28bcaf05b47ce7e81eb0c',1,'BufferProcessor']]]
]
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Blokbox from the source code\&.
