.TH "lightcycle.h" 3 "Sat May 16 2015" "Blokbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lightcycle.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br
\fC#include <QPixmap>\fP
.br
\fC#include <QPainter>\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include <QImage>\fP
.br
\fC#include <QVector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLightCycle\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSEGMENT_HEIGHT\fP   11"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SEGMENT_HEIGHT   11"

.SH "Author"
.PP 
Generated automatically by Doxygen for Blokbox from the source code\&.
