.TH "mainwindow.h" 3 "Sat May 16 2015" "Blokbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mainwindow.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QAudioBuffer>\fP
.br
\fC#include <QAudioDeviceInfo>\fP
.br
\fC#include <QAudioInput>\fP
.br
\fC#include <QAudioProbe>\fP
.br
\fC#include <QDir>\fP
.br
\fC#include <QFileDialog>\fP
.br
\fC#include <QFileInfo>\fP
.br
\fC#include <QHeaderView>\fP
.br
\fC#include <QImage>\fP
.br
\fC#include <QIODevice>\fP
.br
\fC#include <QMainWindow>\fP
.br
\fC#include <QMediaMetaData>\fP
.br
\fC#include <QMediaPlaylist>\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include <QMimeDatabase>\fP
.br
\fC#include <QSettings>\fP
.br
\fC#include <QStandardItemModel>\fP
.br
\fC#include <QString>\fP
.br
\fC#include <QtMultimedia>\fP
.br
\fC#include <QtMultimedia/QMediaPlayer>\fP
.br
\fC#include <QUrl>\fP
.br
\fC#include <QVector>\fP
.br
\fC#include 'fftcalc\&.h'\fP
.br
\fC#include 'playlistmodel\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMainWindow\fP"
.br
.RI "\fIThe \fBMainWindow\fP class is the conductor of this player\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.RI "\fIThis is the namespace that defines the MainWindow1 ui widget\&. This is not the \fBMainWindow\fP class that is defined in this file\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Blokbox from the source code\&.
