.TH "medialibrary.h" 3 "Sat May 16 2015" "Blokbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
medialibrary.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br
\fC#include <QFileSystemModel>\fP
.br
\fC#include <QTreeView>\fP
.br
\fC#include <QAbstractItemModel>\fP
.br
\fC#include <QStandardItemModel>\fP
.br
\fC#include <QStack>\fP
.br
\fC#include <QDir>\fP
.br
\fC#include <QMediaPlayer>\fP
.br
\fC#include <QString>\fP
.br
\fC#include <QSet>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMediaLibrary\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.RI "\fIThis is the namespace that defines the MainWindow1 ui widget\&. This is not the \fBMainWindow\fP class that is defined in this file\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Blokbox from the source code\&.
