.TH "mediainfo.h" 3 "Sat May 16 2015" "Blokbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mediainfo.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'abstractmediainfo\&.h'\fP
.br
\fC#include <QWidget>\fP
.br
\fC#include <QString>\fP
.br
\fC#include <QStandardItemModel>\fP
.br
\fC#include <QStandardItem>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMediaInfo\fP"
.br
.RI "\fIThe \fBMediaInfo\fP class is supposed to be able to display information about the current media that is been played\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.RI "\fIThis is the namespace that defines the MainWindow1 ui widget\&. This is not the \fBMainWindow\fP class that is defined in this file\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Blokbox from the source code\&.
