.TH "playlistmodel.cpp" 3 "Sat May 16 2015" "Blokbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
playlistmodel.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'playlistmodel\&.h'\fP
.br
\fC#include <QFileInfo>\fP
.br
\fC#include <QUrl>\fP
.br
\fC#include <QMediaPlaylist>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Blokbox from the source code\&.
