.TH "Playlist" 3 "Sat May 16 2015" "Blokbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Playlist \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <playlist\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPlaylist\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~Playlist\fP ()"
.br
.ti -1c
.RI "void \fBsetPlaylist\fP (QMediaPlaylist *playlist)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "Ui::Playlist * \fBui\fP"
.br
.ti -1c
.RI "\fBPlaylistModel\fP * \fBmodel\fP"
.br
.ti -1c
.RI "QMediaPlaylist * \fBm_playlist\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Playlist::Playlist (QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.SS "Playlist::~Playlist ()"

.SH "Member Function Documentation"
.PP 
.SS "void Playlist::setPlaylist (QMediaPlaylist * playlist)"

.SH "Member Data Documentation"
.PP 
.SS "QMediaPlaylist* Playlist::m_playlist\fC [private]\fP"

.SS "\fBPlaylistModel\fP* Playlist::model\fC [private]\fP"

.SS "Ui::Playlist* Playlist::ui\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Blokbox from the source code\&.
