.TH "playlistmodel.h" 3 "Sat May 16 2015" "Blokbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
playlistmodel.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QAbstractItemModel>\fP
.br
\fC#include <QMediaPlaylist>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPlaylistModel\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Blokbox from the source code\&.
