.TH "playlist.h" 3 "Sat May 16 2015" "Blokbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
playlist.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br
\fC#include <QMediaPlaylist>\fP
.br
\fC#include 'playlistmodel\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPlaylist\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.RI "\fIThis is the namespace that defines the MainWindow1 ui widget\&. This is not the \fBMainWindow\fP class that is defined in this file\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Blokbox from the source code\&.
