.TH "html/search/search.js" 3 "Sat May 16 2015" "Blokbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
html/search/search.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "function \fBconvertToId\fP (search)"
.br
.ti -1c
.RI "function \fBgetXPos\fP (item)"
.br
.ti -1c
.RI "function \fBgetYPos\fP (item)"
.br
.ti -1c
.RI "function \fBSearchBox\fP (name, resultsPath, inFrame, label)"
.br
.ti -1c
.RI "function \fBSearchResults\fP (name)"
.br
.ti -1c
.RI "function \fBsetKeyActions\fP (elem, action)"
.br
.ti -1c
.RI "function \fBsetClassAttr\fP (elem, attr)"
.br
.ti -1c
.RI "function \fBcreateResults\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBindexSectionsWithContent\fP"
.br
.ti -1c
.RI "var \fBindexSectionNames\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "function convertToId ( search)"

.SS "function createResults ()"

.SS "function getXPos ( item)"

.SS "function getYPos ( item)"

.SS "function SearchBox ( name,  resultsPath,  inFrame,  label)"

.SS "function SearchResults ( name)"

.SS "function setClassAttr ( elem,  attr)"

.SS "function setKeyActions ( elem,  action)"

.SH "Variable Documentation"
.PP 
.SS "var indexSectionNames"
\fBInitial value:\fP
.PP
.nf
=
{
  0: "all",
  1: "classes",
  2: "namespaces",
  3: "files",
  4: "functions",
  5: "variables",
  6: "typedefs",
  7: "enums",
  8: "enumvalues",
  9: "defines",
  10: "pages"
}
.fi
.SS "var indexSectionsWithContent"
\fBInitial value:\fP
.PP
.nf
=
{
  0: "abcdefgilmnoprstuvw~",
  1: "abcflmps",
  2: "u",
  3: "acflmprs",
  4: "abcdefgilmnoprstv~",
  5: "abcdgilmnprstuw",
  6: "c",
  7: "c",
  8: "ct",
  9: "cs",
  10: "b"
}
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Blokbox from the source code\&.
