.TH "spectrograph.h" 3 "Sat May 16 2015" "Blokbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spectrograph.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'abstractspectrograph\&.h'\fP
.br
\fC#include <QWidget>\fP
.br
\fC#include <QPainter>\fP
.br
\fC#include <QPen>\fP
.br
\fC#include <QBrush>\fP
.br
\fC#include <QAudioBuffer>\fP
.br
\fC#include <complex>\fP
.br
\fC#include <QVector>\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include <QTimer>\fP
.br
\fC#include <QGradient>\fP
.br
\fC#include <QAction>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSpectrograph\fP"
.br
.RI "\fIThe \fBSpectrograph\fP class is used to draw the fourier spectrum on the screen\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Blokbox from the source code\&.
