.TH "spectrograph.cpp" 3 "Sat May 16 2015" "Blokbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spectrograph.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'spectrograph\&.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <QtCore/qmath\&.h>\fP
.br
\fC#include <QBrush>\fP
.br
\fC#include <QPen>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <QGradient>\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include <QResizeEvent>\fP
.br
\fC#include <QTimerEvent>\fP
.br
\fC#include <QPainterPath>\fP
.br
\fC#include <QEasingCurve>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Blokbox from the source code\&.
