.TH "html/search/typedefs_0.js" 3 "Sat May 16 2015" "Blokbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
html/search/typedefs_0.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['carray',['CArray',['\&.\&./fft_8h\&.html#a5558954b8bd4dfba6ffb2c046b19da0b',1,'fft\&.h']]],
  ['complex',['Complex',['\&.\&./fft_8h\&.html#a400479783e355a94cc961fb30b81b31f',1,'fft\&.h']]]
]
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Blokbox from the source code\&.
