.TH "Ui" 3 "Sat May 16 2015" "Blokbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui \- This is the namespace that defines the MainWindow1 ui widget\&. This is not the \fBMainWindow\fP class that is defined in this file\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
This is the namespace that defines the MainWindow1 ui widget\&. This is not the \fBMainWindow\fP class that is defined in this file\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Blokbox from the source code\&.
