.TH "html/search/variables_0.js" 3 "Sat May 16 2015" "Blokbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
html/search/variables_0.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['acao',['acao',['\&.\&./class_spectrograph\&.html#adf4a70549ec85adfd8f4e895f75f3ab9',1,'Spectrograph']]],
  ['album',['album',['\&.\&./class_media_info\&.html#a081915c9b96a850a1613d18ccb5a4bbe',1,'MediaInfo']]],
  ['altura',['altura',['\&.\&./class_spectrograph\&.html#a9e8ccf90353a0d9a0a2812d97bf87acf',1,'Spectrograph']]],
  ['array',['array',['\&.\&./class_buffer_processor\&.html#a0386ce6268d24582399897f4e4dae62b',1,'BufferProcessor']]],
  ['artist',['artist',['\&.\&./class_media_info\&.html#ab7020359b32292fe2a5d241aea216af1',1,'MediaInfo']]],
  ['audioinfo',['audioInfo',['\&.\&./class_main_window\&.html#ab8f2a84d55fe8cdd44ccb2ce5448beae',1,'MainWindow']]],
  ['auxplayer',['auxplayer',['\&.\&./class_media_library\&.html#a2d06d3021b0ba046a8d8bca124f26f27',1,'MediaLibrary']]]
]
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Blokbox from the source code\&.
