.TH "html/search/variables_8.js" 3 "Sat May 16 2015" "Blokbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
html/search/variables_8.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['ncols',['ncols',['\&.\&./class_light_cycle\&.html#a08b2280e6a25b33cd18c42908805d754',1,'LightCycle']]],
  ['newspectrum',['newSpectrum',['\&.\&./class_spectrograph\&.html#a6776c7d46a475fb744c01b5fd7c6ec45',1,'Spectrograph']]],
  ['num_5fbands',['NUM_BANDS',['\&.\&./class_spectrograph\&.html#a2ee7c0f9ff6f1c4e91ace1dfb8e1edcb',1,'Spectrograph']]]
]
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Blokbox from the source code\&.
