.TH "html/search/variables_6.js" 3 "Sat May 16 2015" "Blokbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
html/search/variables_6.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['leftlevel',['leftLevel',['\&.\&./class_spectrograph\&.html#aade5d2d8e52f9d9680f95bae06bfccdc',1,'Spectrograph']]],
  ['levelleft',['levelLeft',['\&.\&./class_main_window\&.html#af023943e11a789553a21b125adf04982',1,'MainWindow']]],
  ['levelright',['levelRight',['\&.\&./class_main_window\&.html#a828330fa80915052b6f3e09efed945a6',1,'MainWindow']]],
  ['lightdiameter',['lightDiameter',['\&.\&./class_light_cycle\&.html#a4c5c95dfdcbdb5cdb0227962ca452d0a',1,'LightCycle']]],
  ['logscale',['logscale',['\&.\&./class_buffer_processor\&.html#ac976a4344187a17456f57c378e393a5a',1,'BufferProcessor']]]
]
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Blokbox from the source code\&.
