.TH "html/search/variables_a.js" 3 "Sat May 16 2015" "Blokbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
html/search/variables_a.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['rightlevel',['rightLevel',['\&.\&./class_spectrograph\&.html#aa3426cd81edf016154cfc440d1110f8a',1,'Spectrograph']]],
  ['running',['running',['\&.\&./class_buffer_processor\&.html#a360e29e204008ae2730752f90c382ecd',1,'BufferProcessor']]]
]
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Blokbox from the source code\&.
