.TH "html/search/variables_2.js" 3 "Sat May 16 2015" "Blokbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
html/search/variables_2.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['calculator',['calculator',['\&.\&./class_main_window\&.html#a8e918a1871b3d9f9f0ff6b2a412489c6',1,'MainWindow']]],
  ['chunks',['chunks',['\&.\&./class_buffer_processor\&.html#a5454030dc289375a85d7808b6369e29a',1,'BufferProcessor']]],
  ['codec',['codec',['\&.\&./class_media_info\&.html#a9bfda59d99c98c5e30bece21437e2473',1,'MediaInfo']]],
  ['column',['column',['\&.\&./class_light_cycle\&.html#a89bd82e6cfec676ff803b4545a3a2854',1,'LightCycle']]],
  ['complexframe',['complexFrame',['\&.\&./class_buffer_processor\&.html#a0060adf9a6d0b05fbfc27b1897baa66c',1,'BufferProcessor']]],
  ['compressed',['compressed',['\&.\&./class_buffer_processor\&.html#a457d27e39d2e6edc1467d22bd1eac13d',1,'BufferProcessor']]]
]
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Blokbox from the source code\&.
