.TH "html/search/variables_b.js" 3 "Sat May 16 2015" "Blokbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
html/search/variables_b.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['sample',['sample',['\&.\&./class_main_window\&.html#a96266e232144ae1aa0b59817d6b1e59c',1,'MainWindow']]],
  ['spectrum',['spectrum',['\&.\&./class_buffer_processor\&.html#a2a4bccc444837e9db1baad8379b7be76',1,'BufferProcessor::spectrum()'],['\&.\&./class_main_window\&.html#a120acb602b2b1d9f8d57967dbaf32d2c',1,'MainWindow::spectrum()'],['\&.\&./class_spectrograph\&.html#a296edd5252ddd851fc0f64784b127047',1,'Spectrograph::spectrum()']]],
  ['startcolumn',['startColumn',['\&.\&./class_light_cycle\&.html#a02114b1baddf6017d59e9081aed1bac0',1,'LightCycle']]]
]
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Blokbox from the source code\&.
